name: Manual Singol Release Workflow

on:
  workflow_dispatch:
    inputs:
      loader:
        type: choice
        description: Loaders
        options: 
        - Forge
        - Fabric
        - NeoForge
        - Common
        - All
      platform:
        type: choice
        description: Platforms
        options: 
        - Maven
        - GitHub
        - CurseForge
        - Modrinth     

jobs:

  singol_release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu' # Alternative distribution options are available

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    
    - name: Set permission
      run: chmod +x ./gradlew
      
    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to create releases

      run: |
        ./gradlew wrapper --gradle-version 8.3
        ./gradlew build 
        
    - name: Publish 

      run: |
        ./gradlew publishAll
     
