name: Manual Singol Release Workflow

on:
  workflow_dispatch:
     inputs:
      loader_forge:
        type: boolean
        description: Forge Loader
        default: false
      loader_fabric:
        type: boolean
        description: Fabric Loader
        default: false
      loader_neoforge:
        type: boolean
        description: NeoForge Loader
        default: false
      loader_common:
        type: boolean
        description: |
          Forge Loader:
          Toggle to include Forge loader in the release.
          Enabling this option will include support for Forge mod loader.
        default: false
      platform_maven:
        type: boolean
        description: Publish to Maven
        default: false
      platform_github:
        type: boolean
        description: Publish to GitHub
        default: false
      platform_curseforge:
        type: boolean
        description: Publish to CurseForge
        default: false
      platform_modrinth:
        type: boolean
        description: Publish to Modrinth
        default: false 

jobs:

  singol_release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu' # Alternative distribution options are available

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    
    - name: Set permission
      run: chmod +x ./gradlew
      
    - name: Build
      run: |
        ./gradlew wrapper --gradle-version 8.3
        ./gradlew build 
        
    - name: Set Command
      run: |
          if [ "${{ github.event.inputs.loader }}" == "All" ]; then
            loaders=("Forge" "Fabric" "NeoForge" "Common")
          else
            loaders=("${{ github.event.inputs.loader }}")
          fi

          for loader in "${loaders[@]}"; do
            if [ "${{ github.event.inputs.platform }}" == "Maven" ]; then
              echo "./gradlew publishMaven${loader}"
              # Replace 'echo "./gradlew publishMaven${loader}"' with your actual command
            elif [ "${{ github.event.inputs.platform }}" == "GitHub" ]; then
              echo "./gradlew publishGitHub${loader}"
              # Replace 'echo "./gradlew publishGitHub${loader}"' with your actual command
            elif [ "${{ github.event.inputs.platform }}" == "CurseForge" ]; then
              echo "./gradlew publishCurseForge${loader}"
              # Replace 'echo "./gradlew publishCurseForge${loader}"' with your actual command
            elif [ "${{ github.event.inputs.platform }}" == "Modrinth" ]; then
              echo "./gradlew publishModrinth${loader}"
              # Replace 'echo "./gradlew publishModrinth${loader}"' with your actual command
            fi
          done
